Repository Hacker-GPT/HackerGPT, pull requests merged in 2023-12, with the labels that each got.

#52 Bump @tailwindcss/typography, @types/react-dom, eventsource-parser, t…
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: dependencies

#67 Implement /tools Command and Update Documentation for Available Tools
  README.md
  pages/about-us.tsx
  pages/api/chat.ts
  pages/api/chat/plugins/tools.ts
  pages/api/hackergptstream.ts
Labels: AI efficacy, Frontend, documentation

#73 Add -timeout and -active params to Subfinder tool
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, Backend

#74 Ensure Inclusion of Latest Message in Chatbot Response
  pages/api/chat.ts
Labels: AI efficacy, bug, Backend

#79 Enhance error handling for GKE and adjust the maximum timeout value.
  components/Payments/UpgradeToPremiumPopup.tsx
  pages/api/chat.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/tools.ts
Labels: AI efficacy, Backend

#80 Refactor: Disable -headless flag in Katana due to compatibility issues with Chromium
  pages/api/chat/plugins/katana/katana.content.ts
Labels: bug, Backend

#86 Tranform user query to Subfinder command
  pages/api/chat.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/chat/plugins/tools.ts
  pages/api/openaistream.ts
Labels: AI efficacy, enhancement, Backend

#87 Adjust maximum length limits for entire input, domain, and subdomain in Subfinder
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, Backend

#91 Edit Naabu and Subfinder command Handling and remove full scan option for Naabu
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, Backend

#92 Enable free access to Subfinder tool
  components/EnhancedMenu/ToolSelector.tsx
  pages/api/chat.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/openaistream.ts
Labels: AI efficacy, Backend

#93 Update 'What Makes HackerGPT Special?' content in README and About Us page
  README.md
  pages/about-us.tsx
Labels: Frontend, documentation

#94 Refactor command extraction and AI prompts for Katana integration
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, enhancement, Backend

#95 Implement user query transformation for GAU and Alterx commands
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, enhancement, Backend

#98 97 update outdated dependencies
  .prettierrc
  components/Authorization/LoginSignupPopup.tsx
  components/Chat/Chat.tsx
  components/Chat/ChatInput.tsx
  components/Chat/ChatMessage.tsx
  components/Chat/MemoizedChatMessage.tsx
  components/Chat/ModelSelect.tsx
  components/Chat/PluginSelect.tsx
  components/Chat/VariableModal.tsx
  components/Chatbar/Chatbar.tsx
  components/Chatbar/components/Conversation.tsx
  components/EnhancedMenu/EnhancedMenu.tsx
  components/EnhancedMenu/SearchWeb.tsx
  components/EnhancedMenu/ToolSelector.tsx
  components/Markdown/CodeBlock.tsx
  components/Markdown/MemoizedReactMarkdown.tsx
  components/Payments/UpgradeToPremiumPopup.tsx
  components/Payments/getPremiumStatus.ts
  components/Payments/stripePayments.ts
  components/Settings/SettingDialog.tsx
  hooks/PremiumStatusContext.tsx
  hooks/useCreateReducer.ts
  hooks/useDisplayAttribute.ts
  hooks/useFetch.ts
  hooks/useFocusInputHandler.ts
  package-lock.json
  package.json
  pages/about-us.tsx
  pages/api/chat.ts
  pages/api/chat/completions.ts
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/googlesearch.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/chat/plugins/tools.ts
  pages/api/hackergptstream.ts
  pages/api/home/home.context.tsx
  pages/api/home/home.tsx
  pages/api/openaistream.ts
  services/errorService.ts
  tsconfig.json
  utils/app/clean.ts
  utils/app/conversation.ts
  utils/data/throttle.ts
  vitest.config.ts
Labels: dependencies, code quality ⬆️

#104 Add toggle functionality for Enhance Menu via icon
  components/Chat/Chat.tsx
  components/Chat/ChatInput.tsx
  components/Chat/RenderModuleBenefits.tsx
  components/Chat/VariableModal.tsx
  components/Settings/SettingDialog.tsx
  components/Sidebar/components/OpenCloseButton.tsx
Labels: Frontend

#106 Enhance AI prompt to support large target lists and refine tool flags
  components/Chat/ChatInput.tsx
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, Backend

#107 Integrate httpx tool
  components/EnhancedMenu/ToolSelector.tsx
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/tools.ts
  types/tool.ts
Labels: AI efficacy, enhancement, Backend

#108 Resolved regex syntax issues and enhanced AI with flag property annotations
  pages/api/chat/plugins/httpx/httpx.content.ts
Labels: AI efficacy, bug, Backend

#109 Enhanced Subfinder Functionality with New Flags and AI Prompt
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/chat/plugins/tools.ts
Labels: AI efficacy, Backend

#110 Implement rate limiting for tools
  components/EnhancedMenu/ToolSelector.tsx
  pages/api/chat.ts
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/chat/plugins/tools.ts
Labels: AI efficacy, Backend

#111 Refactor Email Link Method in Popup and Add Warning Message
  components/Authorization/LoginSignupPopup.tsx
  pages/api/chat/plugins/naabu/naabu.content.ts
Labels: Frontend

#112 Fix: Correctly extract IP for `-ip` flag in JSON data parsing
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, bug

#113 Update subscription price to 20/month from 29/month
  components/Payments/UpgradeToPremiumPopup.tsx
Labels: Frontend
