Repository Hacker-GPT/HackerGPT, pull requests merged in 2024-01, with the labels that each got.

#114 90 fix tool select component
  components/EnhancedMenu/ToolSelector.tsx
  components/Settings/SettingDialog.tsx
  package-lock.json
Labels: Frontend, code quality ⬆️

#120 Correct 'invokedByToolId' assignment for accurate 'true' or 'undefined' evaluation
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
Labels: bug, Backend

#121 Add Nuclei tool to Tool Selector, replacing GAU
  components/EnhancedMenu/ToolSelector.tsx
  pages/api/chat/plugins/nuclei/nuclei.content.ts
  pages/api/chat/plugins/tools.ts
  types/tool.ts
Labels: enhancement, Backend

#122 Pass parameters via request body for Katana, HttpX, Naabu and minor tool enhancements
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/nuclei/nuclei.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: code quality ⬆️, Backend

#123 Enhance AI translation prompt for improved response accuracy
  pages/api/hackergptstream.ts
Labels: AI efficacy, Backend

#124 Optimize HackerGPT Token Limit and Pinecone topK for Enhanced Speed and Accuracy
  pages/api/chat.ts
  pages/api/hackergptstream.ts
Labels: AI efficacy, Backend

#125 feat(plugin-store): Implement install/uninstall functionality
  components/Chat/Chat.tsx
  components/Chatbar/Chatbar.tsx
  components/EnhancedMenu/EnhancedMenu.tsx
  components/EnhancedMenu/PluginSelector.tsx
  components/EnhancedMenu/PluginStore.tsx
  components/EnhancedMenu/ToolSelector.tsx
  hooks/PluginProvider.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/api/chat.ts
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/home/home.state.tsx
  pages/api/home/home.tsx
  types/plugin.ts
  types/storage.ts
Labels: enhancement, Backend

#127 Add ratelimit information for GPT-4
  components/Chat/RenderModuleBenefits.tsx
Labels: Frontend

#128 Enhance plugin store UI and implement default plugin installation logic
  components/EnhancedMenu/PluginSelector.tsx
  components/EnhancedMenu/PluginStore.tsx
  hooks/PluginProvider.tsx
  types/plugin.ts
Labels: Frontend

#135 Enhance Menu Layout for 'Regenerate Response' and 'Stop Generating' Buttons
  components/Chat/ChatInput.tsx
Labels: Frontend

#136 Optimize Button Placement for 'Regenerate Response' and 'Stop Generating'
  components/Chat/ChatInput.tsx
Labels: Frontend

#137 Feature Enhancements and UI Updates
  components/Chat/Chat.tsx
  components/Chat/ChatInput.tsx
  components/Chat/hackergpt-svg.tsx
  components/Chatbar/Chatbar.tsx
  components/Chatbar/components/ChatbarSettings.tsx
  components/Mobile/Navbar.tsx
  components/Search/Search.tsx
  components/Search/index.ts
  components/Sidebar/Sidebar.tsx
Labels: Frontend, enhancement, Backend

#138 Pass toolId to firebase function
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/nuclei/nuclei.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/chat/plugins/tools.ts
Labels: Backend

#140 Add plugin store bar under model selector
  components/Chat/Chat.tsx
  components/Chat/ChatInput.tsx
  components/Chat/ModelSelect.tsx
  components/Chat/RenderModuleBenefits.tsx
  components/Chat/VariableModal.tsx
  components/EnhancedMenu/PluginSelector.tsx
  components/EnhancedMenu/PluginStore.tsx
  components/Settings/SettingDialog.tsx
  components/Sidebar/components/OpenCloseButton.tsx
  hooks/PluginProvider.tsx
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/nuclei/nuclei.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  services/useApiService.ts
  types/openai.ts
Labels: Frontend, Backend

#148 Make 'Enhance Search' ON by default
  components/EnhancedMenu/EnhancedSearch.tsx
Labels: AI efficacy, Backend

#149 Normalize command input to lowercase for consistent processing
  components/EnhancedMenu/PluginSelector.tsx
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/httpx/httpx.content.ts
  pages/api/chat/plugins/katana/katana.content.ts
  pages/api/chat/plugins/naabu/naabu.content.ts
  pages/api/chat/plugins/nuclei/nuclei.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
Labels: AI efficacy, Frontend, bug, Backend

#152 Make Alterx, GAU, Subfinder use gpt-4-1106-preview
  pages/api/chat/plugins/alterx/alterx.content.ts
  pages/api/chat/plugins/gau/gau.content.ts
  pages/api/chat/plugins/subfinder/subfinder.content.ts
  pages/api/openaistream.ts
Labels: AI efficacy, Backend

#158 Reverted to Firebase Analytics from Vercel Analytics
  pages/_app.tsx
  utils/server/firebase-client-init.ts
Labels: Backend

#165 Enhance PluginStoreModal with Improved User Feedback and Updated Plugin List Order/Defaults
  components/EnhancedMenu/PluginStore.tsx
  hooks/PluginProvider.tsx
Labels: Frontend

#180 Enhance LoginSignupPopup to open by default for unauthenticated users
  pages/api/home/home.tsx
  tsconfig.json
  utils/server/firebase-client-init.ts
Labels: Frontend
